version: '2'
services:
  postgres:
    image: "postgres:11-alpine"
    container_name: postgres-hydra
    restart: unless-stopped
    ports:
      - '5432:5432'
    volumes:
      - /mnt/disks/data:/var/lib/postgresql/data
    networks:
      - core 
    environment:
      POSTGRES_DB: hydra_testnet
      POSTGRES_USER: hydra
      POSTGRES_PASSWORD: password
      PGDATA: /var/lib/postgresql/data/pgdata
  core:
    image: internetofpeople/hydra-core:latest-testnet
    container_name: hydra-core
    restart: unless-stopped
    command: testnet genesis auto_forge
    ports:
      # P2P
      - '4700:4700' # testnet
      # API
      - '4703:4703'
      # API WALLET
      - '4040:4040'
    cap_add:
      - SYS_NICE
      - SYS_RESOURCE
      - SYS_TIME
    volumes:
      - ./config:/root/config_overwrite
      - ./logs:/root/.local/state/hydra-core
      - ./snapshots:/root/.local/share/hydra-core/testnet/snapshots
    networks:
      - core 
    tty: true
    links:
      - postgres
    depends_on:
      - postgres
  explorer:
    image: internetofpeople/hydra-explorer:latest-local
    container_name: hydra-explorer
    restart: unless-stopped
    ports:
      - '80:80'
    networks:
      - core
    links:
      - core
    depends_on:
      - core

networks:
  core: